rails-ui/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :shopping_cart_items, only: %i[create index]
  resources :orders, only: %i[new create show index]
  patch 'shopping_cart_items/update', to: 'shopping_cart_items#update'
  delete 'shopping_cart_items/delete', to: 'shopping_cart_items#delete'

  resources :products
  devise_for :users
  get 'home/show'
  root 'home#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-ui/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-ui/app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  validates_presence_of :delivery_address

  accepts_nested_attributes_for :order_items

  def total_price
    order_items.map(&:total_price).sum
  end
end

rails-ui/app/models/order_form.rb
class OrderForm
  include ActiveModel::Model
  attr_accessor :order, :payment_information

  def order_attributes=(attributes)
    @order = Order.new(attributes)
  end

  def payment_information_attributes=(attributes)
    @payment_information = PaymentInformation.new(attributes)
  end

  def save
    valid? && order.save
  end

  def valid?
    valid_order = order.valid?
    valid_payment_info = payment_information.valid?
    valid_order && valid_payment_info
  end
end

rails-ui/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates_presence_of :quantity, :unitary_price, :product

  def total_price
    unitary_price * quantity
  end
end

rails-ui/app/models/payment_information.rb
class PaymentInformation
  include ActiveModel::Model
  attr_accessor :credit_card_number, :holder_name, :expiration_date, :security_code

  validates_presence_of :credit_card_number, :holder_name, :expiration_date, :security_code
end

rails-ui/app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :price, :name, :description, :quantity_in_stock, :picture, presence: true
  validates :name, uniqueness: { message: 'name is already taken' }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  has_one_attached :picture
end

rails-ui/app/models/shopping_cart_item.rb
# frozen_string_literal: true

class ShoppingCartItem
  include ActiveModel::Model

  attr_accessor :product, :quantity
end

rails-ui/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails-ui/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

rails-ui/app/controllers/concerns/shopping_cart_concern.rb
# frozen_string_literal: true

module ShoppingCartConcern
  extend ActiveSupport::Concern

  private

  def build_shopping_cart_items_from_session
    (session[:product_ids_list] || '').split(',').reduce([]) do |memo, id|
      already_contained = memo.find { |it| it.product.id == id.to_i }
      if already_contained
        already_contained.quantity = already_contained.quantity + 1
        memo
      else
        p = Product.find(id.to_i)
        memo.push(ShoppingCartItem.new(product: p, quantity: 1))
      end
    end
  end

  def update_shopping_cart_items_in_session(shopping_cart_items)
    session[:product_ids_list] =
      shopping_cart_items
      .flat_map { |item| [item.product.id.to_s] * item.quantity }
      .join(',')
  end
end

rails-ui/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show
    @products = Product.where('quantity_in_stock > 0')
  end
end

rails-ui/app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!
  include ShoppingCartConcern

  def index
    @orders = scoped_orders
  end

  def show
    @order = scoped_orders.find(params[:id])
  end

  def new
    @order_form = OrderForm.new(order: Order.new, payment_information: PaymentInformation.new)
    build_shopping_cart_items_from_session.each do |sci|
      @order_form.order.order_items.build(
        product: sci.product,
        quantity: sci.quantity,
        unitary_price: sci.product.price
      )
    end
  end

  def create
    @order_form = OrderForm.new(order_form_params.to_h.deep_merge({ order_attributes: { user: current_user } }))
    if @order_form.save
      update_shopping_cart_items_in_session([])
      redirect_to home_show_url, notice: 'Checkout completed with success. You should soon receive your delivery.'
    else
      render :new
    end
  end

  private
  def scoped_orders
    Order.includes(:order_items).where(user: current_user)
  end

  def order_form_params
    params.require(:order_form).permit(
      order_attributes: [:delivery_address, order_items_attributes: [:product_id, :unitary_price, :quantity]],
      payment_information_attributes: [:credit_card_number, :holder_name, :expiration_date, :security_code]
    )
  end
end

rails-ui/app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity_in_stock, :picture)
  end
end

rails-ui/app/controllers/shopping_cart_items_controller.rb
# frozen_string_literal: true

class ShoppingCartItemsController < ApplicationController
  include ShoppingCartConcern

  def create
    if session[:product_ids_list].blank?
      session[:product_ids_list] = params[:product_id].to_s
    else
      session[:product_ids_list] += ",#{params[:product_id]}"
    end
    flash[:notice] = 'Item successfully added to your cart'
    redirect_to home_show_path
  end

  def index
    @shopping_cart_items = build_shopping_cart_items_from_session
  end

  def update
    @shopping_cart_items = build_shopping_cart_items_from_session
    shopping_cart_item = @shopping_cart_items.find { |it| it.product.id == params[:product_id].to_i }
    return render status: 404 unless shopping_cart_item

    new_quantity = shopping_cart_item.quantity + params[:increase].to_i
    if new_quantity != 0
      shopping_cart_item.quantity = new_quantity
      update_shopping_cart_items_in_session(@shopping_cart_items)
      return head 204
    end
    @shopping_cart_items = @shopping_cart_items
                           .filter { |item| item.product.id.to_s != params[:product_id] }
    update_shopping_cart_items_in_session(@shopping_cart_items)
    head 204
  end

  def delete
    @shopping_cart_items =
      build_shopping_cart_items_from_session
      .filter { |item| item.product.id.to_s != params[:product_id] }
    update_shopping_cart_items_in_session(@shopping_cart_items)
    head 204
  end

end

rails-ui/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-ui/app/helpers/home_helper.rb
module HomeHelper
end

rails-ui/app/helpers/products_helper.rb
module ProductsHelper
end

rails-ui/app/helpers/shopping_cart_item_helper.rb
module ShoppingCartItemHelper
end

rails-ui/app/views/common/_message_panel.html.erb
<div class="bg-<%= base_color %>-100 border border-<%= base_color %>-400 text-<%= base_color %>-700 px-4 py-3 rounded relative mt-4 mx-4" role="alert" x-data="{ opened: true }" x-show="opened">
  <span class="block sm:inline"><%= yield %></span>
  <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
    <svg class="fill-current h-6 w-6 text-<%= base_color %>-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" @click="opened = false"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
  </span>
</div>

rails-ui/app/views/common/_modal.html.erb
<div
  class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center transition-opacity duration-200 ease-in-out"
  :class="{'opacity-0': !modalOpened, 'pointer-events-none': !modalOpened}"
  x-on:keydown.escape.document="$dispatch('modal-pop')"
>
  <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
  <div class="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
    <div @click="$dispatch('modal-pop')" class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
      <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
      </svg>
      <span class="text-sm">(Esc)</span>
    </div>

    <!-- Add margin if you want to see some of the overlay behind the modal-->
    <div class="modal-content py-4 text-left px-6">
      <!--Title-->
      <div class="flex justify-between items-center pb-3">
        <p class="text-2xl font-bold">Notice</p>
        <div @click="$dispatch('modal-pop')" class="modal-close cursor-pointer z-50">
          <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
          </svg>
        </div>
      </div>

      <!--Body-->
      <p x-html="modalData.content"></p>

      <!--Footer-->
      <div class="flex justify-end pt-2">
        <!-- <button class="px-4 bg-transparent p-3 rounded-lg text-indigo-500 hover:bg-gray-100 hover:text-indigo-400 mr-2" @click="modalOpened = false">Action</button> -->
        <button class="modal-close px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400" @click="$dispatch('modal-pop')">Close</button>
      </div>
    </div>
  </div>
</div>

rails-ui/app/views/common/_page_title.html.erb
<div class="w-full flex justify-center py-8">
  <h1 class="text-lg font-semibold"><%= text %></h1>
</div>

rails-ui/app/views/common/_product_card.html.erb
<div class="product-card max-w-sm rounded overflow-hidden shadow-lg sm:w-full md:w-1/2 lg:w-1/3 xl:w-1/6 m-2 flex flex-col">
  <div class="w-full flex justify-center">
    <%= link_to product_path(product) do %>
      <img src="<%= url_for(product.picture) %>" alt="Product <%= product.name %>">
    <% end %>
  </div>
  <div class="px-6 py-4">
    <%= link_to product.name, product_path(product), class: 'font-bold text-xl mb-2' %>
    <p class="text-gray-700 text-base">
      <%= truncate(product.description, length: 100) %>
    </p>
  </div>
  <div class="px-5 mb-3 flex-grow flex items-end">
    <span class="inline-block text-lg font-semibold text-gray-700 mr-2">U$ <%= product.price %></span>
  </div>
</div>

rails-ui/app/views/home/show.html.erb
<div class="flex flex-wrap justify-center">
  <%= render partial: 'common/product_card', collection: @products, as: :product %>
</div>

rails-ui/app/views/layouts/_navigation.html.erb
<%- unless ['sessions', 'registrations', 'passwords'].include? controller_name %>
  <nav class="flex items-center justify-between flex-wrap bg-pink-500 p-5">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <%= link_to 'Simple Ecommerce RoR MPA', root_path, class: 'font-semibold text-xl tracking-tight' %>
    </div>
    
    <div class="block flex-grow lg:flex lg:items-center lg:w-auto">
      <div class="text-sm lg:flex-grow flex-grow justify-end flex">
        <%- if current_user&.role == 'ADMIN' %>
          <%= link_to 'Products', products_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-3' %>
        <% end %>
        <%- if current_user&.role != 'ADMIN' %>
          <%= link_to 'My Shopping Cart (<span x-text="shoppingCart.length"></span>)'.html_safe,
              shopping_cart_items_path,
              class: 'block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-3'
          %>
          <%- if user_signed_in? %>
            <%= link_to 'My Orders', orders_path,
              class: 'block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-3'
            %>
          <% end %>
        <% end %>
        <%- if user_signed_in? %>
          <%= link_to 'Log out',
            destroy_user_session_path,
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: 'block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white'
          %>
        <% else %>
          <%= link_to 'Log in',
            new_user_session_path,
            class: 'block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white'
          %>
        <% end %>
      </div>
    </div>
  </nav>
<% end %>

rails-ui/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Simple Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body x-data="{
      shoppingCart: [<%= session[:product_ids_list] %>],
      shoppingCartPrices: { <%= (@shopping_cart_items || []).map{ |item| "#{item.product.id}: #{item.product.price}" }.join(",") %> },
      modalOpened: false,
      modalData: {}
    }"
    @modal-push="modalOpened = true; modalData = $event.detail"
    @modal-pop="modalOpened = false"
    :class="{ 'overflow-x-hidden': modalOpened, 'overflow-y-visible': modalOpened }"
  >
    <%= render('layouts/navigation') %>
    <%= render 'common/modal' %>
    <% if notice %>
      <%= render 'common/message_panel', base_color: 'blue' do %>
        <%= notice %>
      <% end %>
    <% end %> 
    <% if alert %>
      <%= render 'common/message_panel', base_color: 'red' do %>
        <%= alert %>
      <% end %>
    <% end %> 
    <%= yield %>
  </body>
</html>

rails-ui/app/views/orders/_order_items.html.erb
<div class="sm:w-10/12 px-5 py-5 border rounded-md">
  <table>
    <thead>
    <tr>
      <th class="w-6/12">Product</th>
      <th class="w-2/12">Quantity</th>
      <th class="w-2/12">Unit. Price</th>
      <th class="w-2/12">Price</th>
    </tr>
    </thead>
    <tbody>
    <% order.order_items.each do |order_item| %>
      <tr>
        <td class="flex items-center">
            <%= image_tag url_for(order_item.product.picture), class: 'h-32 mr-2' %>
            <%= order_item.product.name %>
        </td>
        <td class="text-center"><%= order_item.quantity %></td>
        <td class="text-center"><%= order_item.unitary_price %></td>
        <td class="text-center"><%= order_item.total_price %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="w-full mt-5 text-lg">
    Order total price: <%= order.total_price %>
  </div>
</div>

rails-ui/app/views/orders/index.html.erb
<div class="w-full flex justify-center py-8">
  <h1 class="text-lg font-semibold">Your Orders</h1>
</div>

<table class="table-auto mx-auto mb-3">
  <thead>
    <tr>
      <th class="px-4 py-2">Date</th>
      <th class="px-4 py-2">Total Price</th>
      <th class="px-4 py-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td class="border px-4 py-2"><%= order.created_at %></td>
        <td class="border px-4 py-2"><%= order.total_price %></td>
        <td class="border px-4 py-2"><%= link_to 'Details', order %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails-ui/app/views/orders/new.html.erb
<div class="w-full flex flex-col items-center mt-4">
  <%= render partial: 'order_items', locals: { order: @order_form.order } %>
  <div class="sm:w-10/12 mt-5">
    <% if @order_form.order.errors.any? || @order_form.payment_information.errors.any? %>
      <div id="error_explanation" class="bg-red-400 border border-red-600 mb-3 p-2 rounded-md">
        <h2>The Checkout could not be completed due to the following errors:</h2>
        <ul class="list-disc list-inside">
          <% @order_form.order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          <% @order_form.payment_information.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @order_form, url: orders_path, local: true, class: 'w-full flex flex-col items-center' do |f| %>
      <%= f.fields_for :order do |ff| %>
        <%= ff.label :delivery_address, 'Prease provide your order delivery information', class: 'text-lg text-center mb-2' %>
        <%= ff.text_area :delivery_address, class: 'w-full border rounded-md h-32' %>
        <%= ff.fields_for :order_items do |fff| %>
          <%= fff.hidden_field :product_id %>
          <%= fff.hidden_field :quantity %>
          <%= fff.hidden_field :unitary_price %>
        <% end %>
      <% end %>

      <h2 class="mt-8 text-lg">Payment Information</h2>
      <div class="border rounded-md w-full flex flex-col items-center mt-2">
        <%= f.fields_for :payment_information do |ff| %>
          <div class="px-2 w-full py-3 flex">
            <%= ff.label :credit_card_number, class: 'sm:w-2/12 d-block text-right pr-4' %>
            <%= ff.text_field :credit_card_number, class: 'sm:w-10/12 ipt-primary' %>
          </div>

          <div class="px-2 w-full py-3 flex">
            <%= ff.label :holder_name, class: 'sm:w-2/12 d-block text-right pr-4' %>
            <%= ff.text_field :holder_name, class: 'sm:w-10/12 ipt-primary' %>
          </div>

          <div class="px-2 w-full py-3 flex">
            <%= ff.label :expiration_date, class: 'sm:w-2/12 d-block text-right pr-4' %>
            <%= ff.text_field :expiration_date, class: 'sm:w-4/12 ipt-primary' %>
            <%= ff.label :security_code, class: 'sm:w-2/12 d-block text-right pr-4' %>
            <%= ff.text_field :security_code, class: 'sm:w-4/12 ipt-primary' %>
          </div>
        <% end %>
      </div>

      <%= f.submit 'Complete Checkout', class: 'btn btn-primary my-4' %>
    <% end %>
  </div>
</div>

rails-ui/app/views/orders/show.html.erb
<div class="container mx-auto">
  <div class="flex flex-col p-3 bg-gray-300 border rounded my-3">
    <div>
      <strong>Payment status:</strong>
      APPROVED
    </div>

    <div>
      <strong>Date:</strong>
      <%= @order.created_at %>
    </div>

    <div>
      <strong>Delivery address:</strong>
      <%= simple_format(@order.delivery_address) %>
    </div>
  </div>

  <div class="flex justify-center mb-3">
    <%= render partial: 'order_items', locals: { order: @order } %>
  </div>

  <div class="flex justify-center mb-3">
    <%= link_to 'Back', 'javascript:history.back()', class: 'btn btn-secondary' %>
  </div>
</div>

rails-ui/app/views/products/edit.html.erb
<%= render 'common/page_title', text: 'Editing Product' %>

<%= render 'form', product: @product %>

<div class="flex justify-center mt-3">
  <%= link_to 'Show', @product, class: 'btn btn-primary mr-2' %>
  <%= link_to 'Back', products_path, class: 'btn btn-secondary' %>
</div>

rails-ui/app/views/products/index.html.erb
<div class="w-full flex justify-center py-8">
  <h1 class="text-lg font-semibold">Products</h1>
</div>

<table class="table-auto mx-auto">
  <thead>
    <tr>
      <th class="px-4 py-2">Name</th>
      <th class="px-4 py-2">Price</th>
      <th class="px-4 py-2">Quantity in stock</th>
      <th class="px-4 py-2" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="border px-4 py-2"><%= product.name %></td>
        <td class="border px-4 py-2"><%= product.price %></td>
        <td class="border px-4 py-2"><%= product.quantity_in_stock %></td>
        <td class="border px-4 py-2"><%= link_to 'Show', product %></td>
        <td class="border px-4 py-2"><%= link_to 'Edit', edit_product_path(product) %></td>
        <td class="border px-4 py-2"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="flex justify-center w-full">
  <%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>
</div>

rails-ui/app/views/products/new.html.erb
<%= render 'common/page_title', text: 'New Product' %>

<%= render 'form', product: @product %>

<div class="flex justify-center mt-3">
  <%= link_to 'Back', products_path, class: 'btn btn-secondary' %>
</div>

rails-ui/app/views/products/show.html.erb
<div class="container mx-auto">
  <div class="flex flex-col p-3 bg-gray-300 border rounded my-3">
    <div>
      <strong>Name:</strong>
      <%= @product.name %>
    </div>

    <div>
      <strong>Description:</strong>
      <%= simple_format(@product.description) %>
    </div>

    <div>
      <strong>Price:</strong>
      <%= @product.price %>
    </div>

    <div>
      <strong>Picture:</strong>
      <%- if @product.picture.attached? %>
        <%= image_tag url_for(@product.picture) %>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <div>
        <strong>Quantity in stock:</strong>
        <%= @product.quantity_in_stock %>
      </div>
    <% end %>
  </div>

  <div class="flex justify-center mb-3">
    <% if user_signed_in? && current_user.role == 'ADMIN' %>
      <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary mr-2' %>
    <% else %>
      <%= link_to 'Add to Cart', shopping_cart_items_path(product_id: @product.id), method: :post, class: 'btn btn-primary mr-2' %>
    <% end %>
    <%= link_to 'Back', 'javascript:history.back()', class: 'btn btn-secondary' %>
  </div>
</div>

rails-ui/app/views/shopping_cart_items/create.html.erb
<h1>ShoppingCartItem#create</h1>
<p>Find me in app/views/shopping_cart_item/create.html.erb</p>

rails-ui/app/views/shopping_cart_items/index.html.erb
<div class="flex px-4 py-4">
  <div class="sm:w-10/12">
    <table class="w-full">
      <thead>
        <tr>
          <th class="w-7/12">Product</th>
          <th class="w-3/12">Quantity</th>
          <th class="w-2/12">Price</th>
        </tr>
      </thead>
      <tbody>
        <% @shopping_cart_items.each do |sci| %>
          <tr class="border-b border-gray border-solid" x-show="shoppingCart.indexOf(<%= sci.product.id %>) > -1">
            <td class="flex items-center">
              <%= image_tag url_for(sci.product.picture), class: 'h-40 mr-2' %>
              <%= sci.product.name %>
            </td>
            <td>
              <div class="flex w-full items-center flex-col">
                <div class="flex w-full justify-center">
                  <button
                    @click="patch('<%= shopping_cart_items_update_path(product_id: sci.product.id, increase: -1) %>')
                    .then(() => shoppingCart.splice(shoppingCart.indexOf(<%= sci.product.id %>), 1))"
                  >
                    -
                  </button>
                  <span x-text="shoppingCart.filter(id => id === <%= sci.product.id %>).length"></span>
                  <button
                    @click="patch('<%= shopping_cart_items_update_path(product_id: sci.product.id, increase: +1) %>')
                      .then(() => shoppingCart.push(<%= sci.product.id %>))"
                  >
                  +
                  </button>
                </div>
                <button @click="deleteReq('<%= shopping_cart_items_delete_path(product_id: sci.product.id) %>').then(() => shoppingCart = shoppingCart.filter(item => item !== <%= sci.product.id %>))">
                  Remove
                </button>
              </div>
            </td>
            <td>
              <div class="flex items-center justify-center">
                $ <%= sci.quantity * sci.product.price %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="sm:w-2/12 d-flex flex-col items-stretch">
    <h2>Order summary</h2>
    <div class="mb-5">
      <p>Total: (<span x-text="shoppingCart.length"></span> products)</p>
      <p>$ <span x-text="shoppingCart.reduce((memo, id) => memo + shoppingCartPrices[id], 0)"></span></p>
    </div>
    <% unless user_signed_in? %>
    <button
      class="btn btn-primary w-full"
      x-show="shoppingCart.length > 0"
        @click="$dispatch('modal-push', {
          content: 'In order to proceed with checkout, you need first to ' +
            '<a href=\'<%= new_user_registration_path %>\' class=\'text-indigo-900\'>signup</a>. ' +
            'Or rather <a href=\'<%= new_user_session_path %>\' class=\'text-indigo-900\'>sign in</a> if you are already a registered user.'
        })"
    >
      <i class="fas fa-shopping-basket"></i>
      Continue
    </button>
    <% else %>
    <%= link_to new_order_path, class: 'btn btn-primary w-full block text-center', 'x-show': 'shoppingCart.length > 0' do %>
      <i class="fas fa-shopping-basket"></i>
      Continue
    <% end %>
    <% end %>
  </div>
</div>